export default data = {
  date: "2020-01-01",
  fkUserId: 1,
  healthScore: 10,
  id: 1,
  nutrientsData: {
    Alcohol: 2,
    Caffeine: 10,
    Calcium: 3,
    Calories: 100,
    Carbs: 10,
    Cholesterol: 19,
    Choline: 2,
    Copper: 4,
    Fiber: 12,
    Fluoride: 5,
    Folate: 1,
    Iron: 2,
    Magnesium: 4,
    Manganese: 3,
    Phosphorus: 7,
    Potassium: 8,
    Protein: 13,
    Selenium: 3,
    Sodium: 11,
    Sugar: 17,
    "Total Fat": 23,
    "Vitamin A": 3,
    "Vitamin B1": 6,
    "Vitamin B12": 4,
    "Vitamin B2": 8,
    "Vitamin B3": 3,
    "Vitamin B5": 4,
    "Vitamin B6": 9,
    "Vitamin C": 7,
    "Vitamin D": 4,
    "Vitamin E": 8,
    "Vitamin K": 0,
    Zinc: 4,
  },
  nutrientsUnits: {
    Alcohol: "g",
    Caffeine: "mg",
    Calcium: "mg",
    Calories: "kcal",
    Carbs: "g",
    Cholesterol: "mg",
    Copper: "mg",
    Fiber: "g",
    Folate: "ug",
    Iron: "mg",
    Magnesium: "mg",
    Manganese: "mg",
    Phosphorus: "mg",
    Potassium: "mg",
    Protein: "g",
    Selenium: "ug",
    Sodium: "mg",
    Sugar: "g",
    "Total Fat": "g",
    "Vitamin A": "IU",
    "Vitamin B1": "mg",
    "Vitamin B12": "ug",
    "Vitamin B2": "mg",
    "Vitamin B3": "mg",
    "Vitamin B5": "mg",
    "Vitamin B6": "mg",
    "Vitamin C": "mg",
    "Vitamin D": "ug",
    "Vitamin E": "mg",
    "Vitamin K": "ug",
    Zinc: "mg",
  },
};
